apiVersion: v1
kind: ConfigMap
metadata:
  name: app-utility-qa-pigeon-wfe-config-url-map
  namespace: app-utility-qa
  labels:
    name: app-utility-qa-pigeon-wfe-config-url-map
data:
   
   url_conf: |-
    const isExternal = window.location.host === 'bizmp-qa.marschina.com'
    window.serverConfig = {
    VUE_APP_FILE_API_BASE_URL: isExternal ? 'https://apim-qa.marschina.com/fs' : 'https://apim-qa.mars-ad.net/fs',
    VUE_APP_API_BASE_URL : isExternal ? 'https://apim-qa.marschina.com/pigeon-sss' : 'https://apim-qa.mars-ad.net/pigeon-sss'
    }     
            